export const MAX_HISTORY_COUNT = 100;
export const DEFAULT_WINDOW_WIDTH = 680;
export const DEFAULT_WINDOW_HEIGHT = 720;
export const MIN_WINDOW_WIDTH = 360;
export const MIN_WINDOW_HEIGHT = 480;
export const SEARCH_DEBOUNCE_MS = 150;
export const MAX_CLIPBOARD_TITLE_LENGTH = 200;
export const MAX_CLIPBOARD_NOTE_LENGTH = 10000;
